language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- '4.4.3'
before_install:
- npm config set spin false
- npm install -g npm@^2.15.1
- npm install -g bower
- npm install -g ember
- npm install -g istanbul
install:
- npm install
- bower install
script:
- npm run-script test
- npm run-script coverage
after_success:
- npm run-script build:production
env:
  global:
  - BROCCOLI_ENV="production"
  - secure: AId2fmCn1pLzAIFs4LsI13eL2WV70U0HQVZ8sUxZKSwMkzlWnwfcqkuVeYLSkLctgu5031no0LKO77chQxT/Pu5WkmiKkeXtnvIcAhwMp/7XV1pIH1V3/aL/kuAQ4bd5A94dndFb+QjCyH1cpDFTHho7ibDgwLMPWyA4GkPL8AU=
